from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
import sqlite3

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

DB_FILE = "flip_burgers.db"

# --- DATABASE SETUP INIT ---
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    
    # 1. Create Orders Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            customer_name TEXT,
            phone_number TEXT,
            address_or_table TEXT,
            total_bill INTEGER,
            status TEXT DEFAULT 'Pending'
        )
    ''')
    
    # 2. Create Order Items Table (Connects individual items to an order ID)
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS order_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id INTEGER,
            item_name TEXT,
            quantity INTEGER,
            price INTEGER,
            FOREIGN KEY(order_id) REFERENCES orders(id)
        )
    ''')
    conn.commit()
    conn.close()

init_db()

# --- PRE-SET MENU (Static) ---
MENU = [
    {"id": 1, "name": "The OG Flip Burger", "price": 650, "category": "Beef"},
    {"id": 2, "name": "Double Smashed Flip", "price": 890, "category": "Beef"},
    {"id": 3, "name": "Fiery Zinger Burger", "price": 550, "category": "Chicken"},
    {"id": 4, "name": "Flip Loaded Fries", "price": 450, "category": "Sides"},
    {"id": 5, "name": "Soft Drink", "price": 120, "category": "Drinks"}
]

# --- DATA MODELS ---
class OrderItemInput(BaseModel):
    menu_id: int
    quantity: int

class PlaceOrderInput(BaseModel):
    customer_name: str
    phone_number: str
    address_or_table: str
    items: List[OrderItemInput]

class UpdateStatusInput(BaseModel):
    new_status: str


# --- OPERATIONS ROUTES ---

@app.get("/menu")
def get_menu():
    return MENU

# 1. PLACE ORDER (Saves directly to SQLite)
@app.post("/orders")
def place_order(data: PlaceOrderInput):
    total_bill = 0
    ordered_items_summary = []
    
    # Calculate costs using our static menu
    for item in data.items:
        menu_item = next((m for m in MENU if m["id"] == item.menu_id), None)
        if not menu_item:
            raise HTTPException(status_code=400, detail="Item not found")
        
        item_total = menu_item["price"] * item.quantity
        total_bill += item_total
        ordered_items_summary.append({
            "name": menu_item["name"],
            "quantity": item.quantity,
            "price": menu_item["price"]
        })
    
    # Save into SQLite DB
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    
    cursor.execute('''
        INSERT INTO orders (customer_name, phone_number, address_or_table, total_bill, status)
        VALUES (?, ?, ?, ?, 'Pending')
    ''', (data.customer_name, data.phone_number, data.address_or_table, total_bill))
    
    # Get the unique ID generated by SQLite for this order
    assigned_order_id = cursor.lastrowid
    
    # Save individual lines of items bought
    for item in ordered_items_summary:
        cursor.execute('''
            INSERT INTO order_items (order_id, item_name, quantity, price)
            VALUES (?, ?, ?, ?)
        ''', (assigned_order_id, item["name"], item["quantity"], item["price"]))
        
    conn.commit()
    conn.close()
    
    return {"message": "Order saved to database!", "order_id": assigned_order_id}

# 2. GET ALL ORDERS (For Admin Dashboard)
@app.get("/admin/orders")
def get_all_orders():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row  # Allows accessing columns by name
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM orders ORDER BY id DESC")
    orders = [dict(row) for row in cursor.fetchall()]
    
    for order in orders:
        cursor.execute("SELECT item_name as name, quantity, price FROM order_items WHERE order_id = ?", (order["id"],))
        order["items"] = [dict(item_row) for item_row in cursor.fetchall()]
        order["order_id"] = order["id"]  # UI compatibility
        
    conn.close()
    return orders

# 3. TRACK SPECIFIC ORDER STATUS
@app.get("/track/{order_id}")
def track_order(order_id: int):
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM orders WHERE id = ?", (order_id,))
    order_row = cursor.fetchone()
    
    if not order_row:
        conn.close()
        raise HTTPException(status_code=404, detail="Order not found")
        
    order = dict(order_row)
    cursor.execute("SELECT item_name as name, quantity, price FROM order_items WHERE order_id = ?", (order_id,))
    order["items"] = [dict(item_row) for item_row in cursor.fetchall()]
    order["order_id"] = order["id"]  # UI compatibility
    
    conn.close()
    return order

# 4. UPDATE ORDER STATUS
@app.put("/admin/orders/{order_id}")
def update_order_status(order_id: int, data: UpdateStatusInput):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    
    cursor.execute("UPDATE orders SET status = ? WHERE id = ?", (data.new_status, order_id))
    if cursor.rowcount == 0:
        conn.close()
        raise HTTPException(status_code=404, detail="Order not found")
        
    conn.commit()
    conn.close()
    return {"status": "Database record updated successfully"}